In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('VoviAI_010.csv', encoding='utf-8')
df.head()

,id,createdAt,updatedAt,deletedAt,environment,audioLink,textScriptId,userId,duration,durationInMs,isChecked,isGood,labelerId,reservedAt,needTrim,note,originalAudioLink
0,cb21093c-f179-4694-98a8-66d99e262159,2025-06-24 06:41:12.172437 +00:00,2025-07-03 09:09:53.438948 +00:00,NaN,Noisy,https://voviai.s3.ap-southeast-1.amazonaws.com...,cff08e4f-2920-4b2f-a3db-de8efbbd6b5c,c3b356e7-79ce-4a7d-a15d-32585f8f4bf1,2.0,2368.0,True,True,6b34ddff-3a1b-423a-bab3-71e9d759f4c8,2025-07-03 09:09:51.367000,NaN,NaN,NaN
1,cf1903ec-aadb-47b1-af16-4aa969666a54,2025-06-24 06:41:18.274820 +00:00,2025-07-03 09:23:49.258446 +00:00,NaN,Noisy,https://voviai.s3.ap-southeast-1.amazonaws.com...,7c64ffe0-0a15-41df-b66c-e910009a2439,29efd625-363a-4af8-95b7-feb7198bf420,2.0,1856.0,True,True,6b34ddff-3a1b-423a-bab3-71e9d759f4c8,2025-07-03 09:23:47.455000,NaN,NaN,NaN
2,05000a81-8ebc-4dfe-8302-4e79a5d7e1a3,2025-06-18 03:43:26.023112 +00:00,2025-06-26 17:19:21.708972 +00:00,NaN,Interference,https://voviai.s3.ap-southeast-1.amazonaws.com...,07562090-d8d6-4047-836a-cebb61cb37f6,712ae60c-3f24-4814-b6ee-a5dfba46e452,3.0,4032.0,True,True,9400cfc9-b722-4e49-8ad5-3da6b73403d5,2025-06-26 17:19:10.600000,NaN,NaN,NaN
3,28466e97-5fa5-4de6-8fef-411260699239,2025-06-24 06:41:14.374130 +00:00,2025-06-29 15:38:24.470783 +00:00,NaN,Noisy,https://voviai.s3.ap-southeast-1.amazonaws.com...,b3f407cb-cf04-4df6-bee1-a6276387f387,29efd625-363a-4af8-95b7-feb7198bf420,2.0,2496.0,True,True,3213bfd4-2cfd-480f-ab0b-525764d8487a,2025-06-29 15:38:19.675000,NaN,NaN,NaN
4,439218c6-6b46-4aa3-95c0-cfc5a4150853,2025-06-25 09:12:59.114122 +00:00,2025-06-30 15:18:30.774040 +00:00,NaN,Silent,https://voviai.s3.ap-southeast-1.amazonaws.com...,e2eaaf72-ae4e-47fe-8092-bbc63d847627,69d5dcb8-fc46-42e5-ac23-960a86cfcc27,3.0,3008.0,True,True,5f1a2037-05fe-4c43-8d6f-edaa017a74cf,2025-06-30 15:18:26.829000,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16912 entries, 0 to 16911
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 16912 non-null  object
 1   createdAt          16912 non-null  object
 2   updatedAt          16912 non-null  object
 3   deletedAt          0 non-null      float64
 4   environment        16912 non-null  object
 5   audioLink          16912 non-null  object
 6   textScriptId       16912 non-null  object
 7   userId             16912 non-null  object
 8   duration           14929 non-null  float64
 9   durationInMs       15798 non-null  float64
 10  isChecked          16912 non-null  bool
 11  isGood             16912 non-null  bool
 12  labelerId          16912 non-null  object
 13  reservedAt         16674 non-null  object
 14  needTrim           0 non-null      float64
 15  note               6 non-null      object
 16  originalAudioLink  0 non-null      float64
dtypes: bool(2), float64(5), object(10)
memory usage: 2.0+ MB

In [4]:
user_df = pd.read_csv('user.csv', encoding='utf-8')
user_df.head()

,id,createdAt,updatedAt,deletedAt,username,studentId,gender,accent
0,f637bc15-f56d-4f66-a305-459528da8e38,2025-05-23 02:12:20.142344 +00:00,2025-05-23 02:12:55.905319 +00:00,NaN,duyen,DS170139,Female,Da Nang
1,f0177600-c8e9-408f-9916-57886c9376c3,2025-05-28 08:20:35.901953 +00:00,2025-05-28 08:20:49.973954 +00:00,NaN,Quang,DE190606,Male,Quang Nam
2,54306c0a-97f6-4a66-9aed-73df5d3129be,2025-05-23 02:13:26.207353 +00:00,2025-05-23 02:13:46.990750 +00:00,NaN,XuXu,DS200124,Female,Quang Nam
3,142a33f6-8de7-453e-bc90-22f0ca99e5b9,2025-05-23 02:13:13.557679 +00:00,2025-05-23 02:14:15.806265 +00:00,NaN,Phạm Lê Hùng,DE201082,Male,Gia Lai
4,da97285e-fb5f-42e2-87d3-739be95b7ffb,2025-05-28 08:21:30.063024 +00:00,2025-05-28 08:21:52.379314 +00:00,NaN,Trương Tấn Hưng,DE190532,Male,Da Nang

In [5]:
textscript_df = pd.read_csv('text_script.csv', encoding='utf-8')
textscript_df.head()

,id,createdAt,updatedAt,deletedAt,text
0,326d3ca1-1ab5-460c-b878-593455579f1c,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,“Bàn tay thép” trong nghi lễ biểu thị sức mạnh...
1,cbd2612f-1621-4d3a-94d3-6f0c75b1eb09,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,"“Đạo thể” là vòng tròn trắng lớn, tượng trưng ..."
2,f182c5d9-ea58-4203-904f-8f072f3ba1cc,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,Anh hiền em thảo
3,f75cc2de-a6e0-4a6f-8270-717067716872,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,Cấp Tự vệ Việt Võ Đạo dùng đai xanh màu da trờ...
4,09f9d9f7-8815-4591-b2cc-94bf129fddf7,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,"Cấp Tự vệ Việt Võ Đạo là đai xanh màu da trời,..."

In [6]:
merged_df = pd.merge(df, user_df, left_on='userId', right_on='id', how='inner')
merged_df = pd.merge(merged_df, textscript_df, left_on='textScriptId', right_on='id', how='inner')
merged_df.head()

,id_x,createdAt_x,updatedAt_x,deletedAt_x,environment,audioLink,textScriptId,userId,duration,durationInMs,...,deletedAt_y,username,studentId,gender,accent,id,createdAt,updatedAt,deletedAt,text
0,cb21093c-f179-4694-98a8-66d99e262159,2025-06-24 06:41:12.172437 +00:00,2025-07-03 09:09:53.438948 +00:00,NaN,Noisy,https://voviai.s3.ap-southeast-1.amazonaws.com...,cff08e4f-2920-4b2f-a3db-de8efbbd6b5c,c3b356e7-79ce-4a7d-a15d-32585f8f4bf1,2.0,2368.0,...,NaN,Đinh Ngọc Minh,DE200145,Male,Quang Nam,cff08e4f-2920-4b2f-a3db-de8efbbd6b5c,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,Truyền bá võ thuật cho quần chúng
1,cf1903ec-aadb-47b1-af16-4aa969666a54,2025-06-24 06:41:18.274820 +00:00,2025-07-03 09:23:49.258446 +00:00,NaN,Noisy,https://voviai.s3.ap-southeast-1.amazonaws.com...,7c64ffe0-0a15-41df-b66c-e910009a2439,29efd625-363a-4af8-95b7-feb7198bf420,2.0,1856.0,...,NaN,Nguyễn Lê Đăng Khoa,DE200361,Male,Thua Thien Hue,7c64ffe0-0a15-41df-b66c-e910009a2439,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,Người cao tuổi hơn
2,05000a81-8ebc-4dfe-8302-4e79a5d7e1a3,2025-06-18 03:43:26.023112 +00:00,2025-06-26 17:19:21.708972 +00:00,NaN,Interference,https://voviai.s3.ap-southeast-1.amazonaws.com...,07562090-d8d6-4047-836a-cebb61cb37f6,712ae60c-3f24-4814-b6ee-a5dfba46e452,3.0,4032.0,...,NaN,Nguyễn Nhật Toàn,DE190087,Male,Quang Nam,07562090-d8d6-4047-836a-cebb61cb37f6,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,Mùa thu năm 1939 là thời điểm VOVINAM biểu diễ...
3,28466e97-5fa5-4de6-8fef-411260699239,2025-06-24 06:41:14.374130 +00:00,2025-06-29 15:38:24.470783 +00:00,NaN,Noisy,https://voviai.s3.ap-southeast-1.amazonaws.com...,b3f407cb-cf04-4df6-bee1-a6276387f387,29efd625-363a-4af8-95b7-feb7198bf420,2.0,2496.0,...,NaN,Nguyễn Lê Đăng Khoa,DE200361,Male,Thua Thien Hue,b3f407cb-cf04-4df6-bee1-a6276387f387,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,Việt Võ Đạo Sinh nhìn lại những bước đã qua
4,439218c6-6b46-4aa3-95c0-cfc5a4150853,2025-06-25 09:12:59.114122 +00:00,2025-06-30 15:18:30.774040 +00:00,NaN,Silent,https://voviai.s3.ap-southeast-1.amazonaws.com...,e2eaaf72-ae4e-47fe-8092-bbc63d847627,69d5dcb8-fc46-42e5-ac23-960a86cfcc27,3.0,3008.0,...,NaN,nhat,DE181043,Male,Da Nang,e2eaaf72-ae4e-47fe-8092-bbc63d847627,2025-05-04 17:46:11.265093 +00:00,2025-05-04 17:46:11.265093 +00:00,NaN,Địa điểm qua đời của Nguyễn Lộc là ở Sài Gòn

In [7]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16912 entries, 0 to 16911
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_x               16912 non-null  object
 1   createdAt_x        16912 non-null  object
 2   updatedAt_x        16912 non-null  object
 3   deletedAt_x        0 non-null      float64
 4   environment        16912 non-null  object
 5   audioLink          16912 non-null  object
 6   textScriptId       16912 non-null  object
 7   userId             16912 non-null  object
 8   duration           14929 non-null  float64
 9   durationInMs       15798 non-null  float64
 10  isChecked          16912 non-null  bool
 11  isGood             16912 non-null  bool
 12  labelerId          16912 non-null  object
 13  reservedAt         16674 non-null  object
 14  needTrim           0 non-null      float64
 15  note               6 non-null      object
 16  originalAudioLink  0 non-null      float64
 17  id_y               16912 non-null  object
 18  createdAt_y        16912 non-null  object
 19  updatedAt_y        16912 non-null  object
 20  deletedAt_y        0 non-null      float64
 21  username           16912 non-null  object
 22  studentId          16912 non-null  object
 23  gender             16912 non-null  object
 24  accent             16912 non-null  object
 25  id                 16912 non-null  object
 26  createdAt          16912 non-null  object
 27  updatedAt          16912 non-null  object
 28  deletedAt          0 non-null      float64
 29  text               16912 non-null  object
dtypes: bool(2), float64(7), object(21)
memory usage: 3.6+ MB

In [8]:
central = [
    "Thanh Hoa", "Nghe An", "Ha Tinh", "Quang Binh", "Quang Tri", "Thua Thien Hue", "Da Nang",
    "Quang Nam", "Quang Ngai", "Binh Dinh", "Phu Yen", "Khanh Hoa", "Ninh Thuan", "Binh Thuan",
    "Kon Tum", "Gia Lai", "Dak Lak", "Dak Nong", "Lam Dong"
]


north = [
    "Ha Noi", "Ha Giang", "Cao Bang", "Lao Cai", "Bac Kan", "Lang Son", "Tuyen Quang", "Yen Bai",
    "Thai Nguyen", "Phu Tho", "Bac Giang", "Quang Ninh", "Bac Ninh", "Hung Yen", "Hai Duong",
    "Hai Phong", "Vinh Phuc", "Nam Dinh", "Thai Binh", "Ha Nam", "Ninh Binh", "Hoa Binh", "Son La",
    "Dien Bien", "Lai Chau"
]

south = [
    "Ho Chi Minh", "Binh Duong", "Dong Nai", "Ba Ria - Vung Tau", "Tay Ninh", "Binh Phuoc",
    "Long An", "Tien Giang", "Ben Tre", "Tra Vinh", "Vinh Long", "Dong Thap",
    "An Giang", "Kien Giang", "Can Tho", "Hau Giang", "Soc Trang", "Bac Lieu", "Ca Mau"
]

In [9]:
new_df = merged_df[['audioLink', 'text', 'userId', 'environment', 'gender', 'accent']].copy()
new_df.head()

,audioLink,text,userId,environment,gender,accent
0,https://voviai.s3.ap-southeast-1.amazonaws.com...,Truyền bá võ thuật cho quần chúng,c3b356e7-79ce-4a7d-a15d-32585f8f4bf1,Noisy,Male,Quang Nam
1,https://voviai.s3.ap-southeast-1.amazonaws.com...,Người cao tuổi hơn,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,Male,Thua Thien Hue
2,https://voviai.s3.ap-southeast-1.amazonaws.com...,Mùa thu năm 1939 là thời điểm VOVINAM biểu diễ...,712ae60c-3f24-4814-b6ee-a5dfba46e452,Interference,Male,Quang Nam
3,https://voviai.s3.ap-southeast-1.amazonaws.com...,Việt Võ Đạo Sinh nhìn lại những bước đã qua,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,Male,Thua Thien Hue
4,https://voviai.s3.ap-southeast-1.amazonaws.com...,Địa điểm qua đời của Nguyễn Lộc là ở Sài Gòn,69d5dcb8-fc46-42e5-ac23-960a86cfcc27,Silent,Male,Da Nang

In [10]:
def get_region(accent):
	if accent in central:
		return 'Central'
	elif accent in north:
		return 'North'
	elif accent in south:
		return 'South'
	else:
		return 'Unknown'

new_df['region'] = new_df['accent'].apply(get_region)

In [11]:
new_df.rename(columns={'accent': 'province_name'}, inplace=True)

new_df.head()

,audioLink,text,userId,environment,gender,province_name,region
0,https://voviai.s3.ap-southeast-1.amazonaws.com...,Truyền bá võ thuật cho quần chúng,c3b356e7-79ce-4a7d-a15d-32585f8f4bf1,Noisy,Male,Quang Nam,Central
1,https://voviai.s3.ap-southeast-1.amazonaws.com...,Người cao tuổi hơn,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,Male,Thua Thien Hue,Central
2,https://voviai.s3.ap-southeast-1.amazonaws.com...,Mùa thu năm 1939 là thời điểm VOVINAM biểu diễ...,712ae60c-3f24-4814-b6ee-a5dfba46e452,Interference,Male,Quang Nam,Central
3,https://voviai.s3.ap-southeast-1.amazonaws.com...,Việt Võ Đạo Sinh nhìn lại những bước đã qua,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,Male,Thua Thien Hue,Central
4,https://voviai.s3.ap-southeast-1.amazonaws.com...,Địa điểm qua đời của Nguyễn Lộc là ở Sài Gòn,69d5dcb8-fc46-42e5-ac23-960a86cfcc27,Silent,Male,Da Nang,Central

In [12]:
new_df['gender'] = new_df['gender'].map({'Female': 0, 'Male': 1})

new_df.rename(columns={'userId': 'speakerId'}, inplace=True)

new_df.head(10)

,audioLink,text,speakerId,environment,gender,province_name,region
0,https://voviai.s3.ap-southeast-1.amazonaws.com...,Truyền bá võ thuật cho quần chúng,c3b356e7-79ce-4a7d-a15d-32585f8f4bf1,Noisy,1,Quang Nam,Central
1,https://voviai.s3.ap-southeast-1.amazonaws.com...,Người cao tuổi hơn,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,1,Thua Thien Hue,Central
2,https://voviai.s3.ap-southeast-1.amazonaws.com...,Mùa thu năm 1939 là thời điểm VOVINAM biểu diễ...,712ae60c-3f24-4814-b6ee-a5dfba46e452,Interference,1,Quang Nam,Central
3,https://voviai.s3.ap-southeast-1.amazonaws.com...,Việt Võ Đạo Sinh nhìn lại những bước đã qua,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,1,Thua Thien Hue,Central
4,https://voviai.s3.ap-southeast-1.amazonaws.com...,Địa điểm qua đời của Nguyễn Lộc là ở Sài Gòn,69d5dcb8-fc46-42e5-ac23-960a86cfcc27,Silent,1,Da Nang,Central
5,https://voviai.s3.ap-southeast-1.amazonaws.com...,Điều tâm niệm thứ mười của Việt Võ Đạo Sinh,ccee70e2-fc24-4192-865a-64752afeaf4c,Noisy,1,Quang Binh,Central
6,https://voviai.s3.ap-southeast-1.amazonaws.com...,"Phù hiệu Việt Võ Đạo có màu nền vàng nổi bật, ...",1a509583-eddf-4bb4-9c1c-47fb2ff4b64d,Noisy,0,Da Nang,Central
7,https://voviai.s3.ap-southeast-1.amazonaws.com...,"Cương trực là sự thẳng thắn, kiên quyết trong ...",56bdc899-ac72-4502-b228-6f74cacdf8f5,Noisy,0,Gia Lai,Central
8,https://voviai.s3.ap-southeast-1.amazonaws.com...,Hoàng đai cấp 2 có danh xưng là huấn luyện viê...,2a60552e-77ff-4cf2-ab72-dc199d6ff32a,Noisy,1,Quang Ngai,Central
9,https://voviai.s3.ap-southeast-1.amazonaws.com...,Hướng đi đã được vạch ra,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,1,Thua Thien Hue,Central

In [13]:
new_df.to_csv('VoviAI_010_cleaned.csv', index=False, encoding='utf-8')

In [14]:
clean_df = pd.read_csv('VoviAI_010_cleaned.csv', encoding='utf-8')
clean_df.head()

,audioLink,text,speakerId,environment,gender,province_name,region
0,https://voviai.s3.ap-southeast-1.amazonaws.com...,Truyền bá võ thuật cho quần chúng,c3b356e7-79ce-4a7d-a15d-32585f8f4bf1,Noisy,1,Quang Nam,Central
1,https://voviai.s3.ap-southeast-1.amazonaws.com...,Người cao tuổi hơn,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,1,Thua Thien Hue,Central
2,https://voviai.s3.ap-southeast-1.amazonaws.com...,Mùa thu năm 1939 là thời điểm VOVINAM biểu diễ...,712ae60c-3f24-4814-b6ee-a5dfba46e452,Interference,1,Quang Nam,Central
3,https://voviai.s3.ap-southeast-1.amazonaws.com...,Việt Võ Đạo Sinh nhìn lại những bước đã qua,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,1,Thua Thien Hue,Central
4,https://voviai.s3.ap-southeast-1.amazonaws.com...,Địa điểm qua đời của Nguyễn Lộc là ở Sài Gòn,69d5dcb8-fc46-42e5-ac23-960a86cfcc27,Silent,1,Da Nang,Central

In [15]:
import re

def clean_text(text):
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[“”"‘’•@#$%^&*+=\[\]{}|\\:<>]', '', text)
    text = re.sub(r'\s+', ' ', text)
    text = text.strip().lower()
    return text

example_text = clean_df['text'].iloc[5]
cleaned_text = clean_text(example_text)

print(f"Original text: {example_text}")
print(f"Cleaned text: {cleaned_text}")

Original text: Điều tâm niệm thứ mười của Việt Võ Đạo Sinh
Cleaned text: điều tâm niệm thứ mười của việt võ đạo sinh

In [16]:
clean_df['text'] = clean_df['text'].apply(clean_text)
clean_df.head()

,audioLink,text,speakerId,environment,gender,province_name,region
0,https://voviai.s3.ap-southeast-1.amazonaws.com...,truyền bá võ thuật cho quần chúng,c3b356e7-79ce-4a7d-a15d-32585f8f4bf1,Noisy,1,Quang Nam,Central
1,https://voviai.s3.ap-southeast-1.amazonaws.com...,người cao tuổi hơn,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,1,Thua Thien Hue,Central
2,https://voviai.s3.ap-southeast-1.amazonaws.com...,mùa thu năm 1939 là thời điểm vovinam biểu diễ...,712ae60c-3f24-4814-b6ee-a5dfba46e452,Interference,1,Quang Nam,Central
3,https://voviai.s3.ap-southeast-1.amazonaws.com...,việt võ đạo sinh nhìn lại những bước đã qua,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,1,Thua Thien Hue,Central
4,https://voviai.s3.ap-southeast-1.amazonaws.com...,địa điểm qua đời của nguyễn lộc là ở sài gòn,69d5dcb8-fc46-42e5-ac23-960a86cfcc27,Silent,1,Da Nang,Central

In [17]:
clean_df.to_csv('VoviAI_010_cleaned_final.csv', index=False, encoding='utf-8')

In [18]:
final_df = pd.read_csv('VoviAI_010_cleaned_final.csv', encoding='utf-8')
final_df.head()

,audioLink,text,speakerId,environment,gender,province_name,region
0,https://voviai.s3.ap-southeast-1.amazonaws.com...,truyền bá võ thuật cho quần chúng,c3b356e7-79ce-4a7d-a15d-32585f8f4bf1,Noisy,1,Quang Nam,Central
1,https://voviai.s3.ap-southeast-1.amazonaws.com...,người cao tuổi hơn,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,1,Thua Thien Hue,Central
2,https://voviai.s3.ap-southeast-1.amazonaws.com...,mùa thu năm 1939 là thời điểm vovinam biểu diễ...,712ae60c-3f24-4814-b6ee-a5dfba46e452,Interference,1,Quang Nam,Central
3,https://voviai.s3.ap-southeast-1.amazonaws.com...,việt võ đạo sinh nhìn lại những bước đã qua,29efd625-363a-4af8-95b7-feb7198bf420,Noisy,1,Thua Thien Hue,Central
4,https://voviai.s3.ap-southeast-1.amazonaws.com...,địa điểm qua đời của nguyễn lộc là ở sài gòn,69d5dcb8-fc46-42e5-ac23-960a86cfcc27,Silent,1,Da Nang,Central

In [19]:
from sklearn.model_selection import train_test_split

unique_speakers = clean_df['speakerId'].unique()

train_speakers, temp_speakers = train_test_split(unique_speakers, test_size=0.2, random_state=42)
val_speakers, test_speakers = train_test_split(temp_speakers, test_size=0.5, random_state=42)

train_df = clean_df[clean_df['speakerId'].isin(train_speakers)]
val_df = clean_df[clean_df['speakerId'].isin(val_speakers)]
test_df = clean_df[clean_df['speakerId'].isin(test_speakers)]

print(f"Train set size: {len(train_df)}")
print(f"Validation set size: {len(val_df)}")
print(f"Test set size: {len(test_df)}")

Train set size: 13264
Validation set size: 1847
Test set size: 1801

In [20]:
train_df.to_csv("train.csv", index=False)
val_df.to_csv("val.csv", index=False)
test_df.to_csv("test.csv", index=False)

In [21]:
from datasets import Dataset, DatasetDict

dataset = DatasetDict({
    "train": Dataset.from_pandas(train_df),
    "validation": Dataset.from_pandas(val_df),
    "test": Dataset.from_pandas(test_df)
})

In [1]:
from huggingface_hub import login
from dotenv import load_dotenv
load_dotenv()

import os

login(token=os.getenv("HF_TOKEN"))

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [23]:
dataset.push_to_hub("minhtien2405/VoviAIDataset", private=True)

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/14 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

CommitInfo(commit_url='https://huggingface.co/datasets/minhtien2405/VoviAIDataset/commit/8299614bfbdc354944d676667a3ffbabb96bd9ac', commit_message='Upload dataset', commit_description='', oid='8299614bfbdc354944d676667a3ffbabb96bd9ac', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/minhtien2405/VoviAIDataset', endpoint='https://huggingface.co', repo_type='dataset', repo_id='minhtien2405/VoviAIDataset'), pr_revision=None, pr_num=None)

In [5]:
from datasets import load_dataset

# load dataset from hf hub minhttien2405/VoviDataset
dataset = load_dataset("minhtien2405/VoviAIDataset")
dataset

README.md:   0%|          | 0.00/761 [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/1.12M [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/140k [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/141k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/13264 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1847 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1801 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['audioLink', 'text', 'speakerId', 'environment', 'gender', 'province_name', 'region', '__index_level_0__'],
        num_rows: 13264
    })
    validation: Dataset({
        features: ['audioLink', 'text', 'speakerId', 'environment', 'gender', 'province_name', 'region', '__index_level_0__'],
        num_rows: 1847
    })
    test: Dataset({
        features: ['audioLink', 'text', 'speakerId', 'environment', 'gender', 'province_name', 'region', '__index_level_0__'],
        num_rows: 1801
    })
})